name: "Build Models Nuget Package"

on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Set VERSION variable from tag
    run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

  - name: Pack
    run: dotnet pack ModelSaber.Models/ModelSaber.Models.csproj -c Release /p:Version=${VERSION}

  - name: Prep packages
    run: dotnet nuget add source --username ${{ secrets.GITHUB_USER }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ModelSaber/index.json"

  - name: Publish to GitHub packages
    run: dotnet nuget push ModelSaber.Models/bin/Release/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"