name: "Build Models Nuget Package"

on: 
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish:
    name: Build Pack Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

    - name: Build
      run: dotnet build ModelSaber.Models/ModelSaber.Models.csproj -c Release /p:Version=${VERSION} 

    - name: Pack
      run: dotnet pack ModelSaber.Models/ModelSaber.Models.csproj -c Release /p:Version=${VERSION}

    - name: Prep packages
      run: dotnet nuget add source --username ${{ secrets.RUNNER_USER }} --password ${{ secrets.RUNNER_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ModelSaber/index.json"

    - name: Publish to GitHub packages
      run: dotnet nuget push ModelSaber.Models/bin/Release/ModelSaber.Models.${VERSION}.nupkg --api-key ${{ secrets.RUNNER_TOKEN }} --source "github"